name: Build Javadocs and Deploy to Github Pages
on:
  workflow_dispatch:
  push:
    tags:
      - '*'
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up build JDK
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
        with:
          distribution: 'zulu'
          java-version: '21'
          check-latest: true
      - name: Build Javadoc
        run: ./mvnw -B -V -e javadoc:javadoc
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@62fec3add6773ec5dbbf18d2ee4260911aa35cf4 # v4.6.9
        with:
          folder: target/site/apidocs
          target-folder: ${{github.ref_name}}
